# Generated by Django 5.0.14 on 2026-10-03 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epos_qbo', '0017_qbowebhookevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runjob',
            name='scope',
            field=models.CharField(choices=[('portal_review', 'Company A review'), ('single_company', 'Single Company'), ('all_companies', 'All Companies'), ('inventory_pipeline', 'Inventory'), ('inventory_sync', 'Inventory Sync')], max_length=32),
        ),
        migrations.CreateModel(
            name='PortalReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('confirmation_id', models.CharField(max_length=64, unique=True)),
                ('result', models.TextField(blank=True, default='Queued')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='review_action', to='epos_qbo.runjob')),
            ],
            options={
                'permissions': [('can_approve_company_a_reviews', 'Can approve Company A reviews')],
            },
        ),
    ]
