# Generated by Django 5.0.14 on 2026-10-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epos_qbo', '0018_portal_review_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runjob',
            name='scope',
            field=models.CharField(choices=[('workspace_read', 'Company records update'), ('portal_review', 'Company A review'), ('single_company', 'Single Company'), ('all_companies', 'All Companies'), ('inventory_pipeline', 'Inventory'), ('inventory_sync', 'Inventory Sync')], max_length=32),
        ),
    ]
