# Generated by Django 5.0.14 on 2026-10-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epos_qbo', '0019_alter_runjob_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalSettingChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_key', models.SlugField(max_length=64)),
                ('setting', models.CharField(max_length=120)),
                ('old_value', models.CharField(blank=True, default='', max_length=200)),
                ('new_value', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('actor', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
