# Generated by Django 5.0.14 on 2026-10-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epos_qbo', '0020_portal_setting_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runjob',
            name='scope',
            field=models.CharField(choices=[('workspace_read', 'Company records update'), ('portal_review', 'Company A review'), ('single_company', 'Single Company'), ('all_companies', 'All Companies'), ('inventory_pipeline', 'Inventory'), ('inventory_sync', 'Inventory Sync'), ('company_a_daily', 'Nora daily routine')], max_length=32),
        ),
        migrations.AlterField(
            model_name='runschedule',
            name='scope',
            field=models.CharField(choices=[('single_company', 'Single Company'), ('all_companies', 'All Companies'), ('inventory_pipeline', 'Inventory'), ('inventory_sync', 'Inventory Sync'), ('company_a_daily', 'Nora daily routine')], default='all_companies', max_length=32),
        ),
        migrations.AlterField(
            model_name='runscheduleevent',
            name='event_type',
            field=models.CharField(choices=[('queued', 'Queued'), ('skipped_overlap', 'Skipped Overlap'), ('skipped_invalid', 'Skipped Invalid'), ('error', 'Error'), ('one_time_completed', 'One-time Completed'), ('fallback_enabled', 'Fallback Enabled'), ('fallback_disabled', 'Fallback Disabled'), ('run_succeeded', 'Run Succeeded'), ('run_failed', 'Run Failed'), ('skipped_missed', 'Skipped: missed while the worker was offline'), ('skipped_done', 'Skipped: that business day already ran'), ('skipped_not_owner', 'Skipped: another scheduler owns this workflow')], max_length=32),
        ),
    ]
