# Generated by Django 5.0.14 on 2026-10-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epos_qbo', '0022_remove_legacy_schedules'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventoryReviewAcknowledgement',
        ),
    ]
