from django.urls import path

from . import views, views_company_a, views_attention, views_experience, views_workspace, webhooks

app_name = "epos_qbo"

urlpatterns = [
    path("companies/<slug:company_key>/records/update/", views_workspace.update, name="workspace-update"),
    path("companies/<slug:company_key>/deposit-settings/", views_workspace.deposit_settings, name="deposit-settings"),
    path("admin/", views_experience.admin_home, name="admin-home"),
    path("attention/", views_attention.inbox, name="attention"),
    path("attention/confirm/", views_attention.confirm, name="attention-confirm"),
    path("", views.overview, name="overview-root"),
    path("dashboard/", views.overview, name="overview"),
    path("dashboard/panels/", views.overview_panels, name="overview-panels"),
    path("runs/", views.runs_list, name="runs"),
    path("runs/trigger", views.trigger_run, name="run-trigger"),
    path("runs/<uuid:job_id>/", views.run_detail, name="run-detail"),
    path(
        "runs/<uuid:job_id>/artifacts/<int:artifact_id>/report/<slug:report_key>/",
        views.run_artifact_report,
        name="run-artifact-report",
    ),
    path("runs/<uuid:job_id>/logs", views.run_logs, name="run-logs"),
    path("api/runs/active", views.run_active_ids, name="run-active-ids"),
    path("api/runs/status", views.run_status_check, name="run-status-check"),
    path("company-a/daily-runs/", views_company_a.company_a_runs, name="company-a-runs"),
    path(
        "company-a/daily-runs/<str:business_date>/<str:run_id>/",
        views_company_a.company_a_run_detail,
        name="company-a-run-detail",
    ),
    path(
        "company-a/daily-runs/<str:business_date>/<str:run_id>/file/",
        views_company_a.company_a_evidence,
        name="company-a-evidence",
    ),
    path("logs/", views_experience.daily_activity, name="logs"),
    path("schedules/", views.schedules_page, name="schedules"),
    path("schedules/status/", views.schedule_status_api, name="schedule-status"),
    path("schedules/create", views.schedule_create, name="schedule-create"),
    path("schedules/<uuid:schedule_id>/update", views.schedule_update, name="schedule-update"),
    path("schedules/<uuid:schedule_id>/toggle", views.schedule_toggle, name="schedule-toggle"),
    path("schedules/<uuid:schedule_id>/run-now", views.schedule_run_now, name="schedule-run-now"),
    path("schedules/<uuid:schedule_id>/delete", views.schedule_delete, name="schedule-delete"),
    path("companies/", views.companies_list, name="companies-list"),
    path("companies/new", views.company_new, name="company-new"),
    path("companies/<slug:company_key>/", views.company_detail, name="company-detail"),
    path("companies/<slug:company_key>/toggle-active/", views.company_toggle_active, name="company-toggle-active"),
    path("companies/<slug:company_key>/advanced", views.company_advanced, name="company-advanced"),
    path("companies/<slug:company_key>/sync-json", views.sync_company_json, name="company-sync-json"),
    path("settings/", views.settings_page, name="settings"),
    path("api-tokens/", views.api_tokens_page, name="api-tokens"),
    path("api-tokens/<slug:company_key>/test/", views.api_tokens_test, name="api-tokens-test"),
    path("api-tokens/<slug:company_key>/refresh/", views.api_tokens_refresh, name="api-tokens-refresh"),
    path("tools/", views.tools_page, name="tools"),
    path("tools/qbo-query/", views.tools_qbo_query_api, name="tools-qbo-query"),
    path("tools/verify-mapping/", views.tools_verify_mapping_api, name="tools-verify-mapping"),
    path("webhooks/quickbooks/", webhooks.quickbooks_webhook, name="quickbooks-webhook"),
    path("webhooks/quickbooks", webhooks.quickbooks_webhook, name="quickbooks-webhook-noslash"),
]
